<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>FaceBookSignUp</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-03-02T03:26:43</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2b5b5da5-9ab3-4220-834f-4de99247a472</testSuiteGuid>
   <testCaseLink>
      <guid>81fba1ec-c17e-443d-a637-1207296f10a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Facebook Signup/Failed if All Field Value Blank</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a675f070-8439-4022-9eb5-463a4cfc468f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Facebook Signup/Failed if Re-Enter Email not Match</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>73cfa7f0-b1b2-4b83-82f3-ffbd2ab42bc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Facebook Signup/Success Sign Up Facebook With Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14507ad3-48a5-4358-bf7f-04fcf9ed3923</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9394b881-96d0-4cdf-a429-ccd0781698bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3951311f-ef62-47da-913b-cce5cfdd6784</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e6a5fc-b246-4e59-bf22-6cd2cb00a00a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72fc3024-851d-486b-a943-d8d588639ece</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbce937f-9596-425c-9f65-dee2d9f860cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8821ffe-55c9-4f9b-999b-897471cd061f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fd8caeb3-1655-4395-a762-b179660b5990</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Facebook Signup/Success Sign Up Facebook With Phone Number</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feb6304e-7690-4357-9faf-dbff2b5c3f8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc647214-50c0-471e-9631-36817dc398f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb920e47-0587-40d8-bfa9-fd209a7e0750</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9360a4a6-6844-4039-b0ff-30ca1a604056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3341a22a-f65d-459a-b745-ec1ebc45827d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa71caa8-7eaf-4165-b9bf-4a712e6fd593</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8567b619-f845-47d9-a912-6b754e0355fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d162871f-5844-45e3-b135-1f1ea7f82a64</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
